version: "3"

services:
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATABASE
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PASSWORD
    ports:
      - $PG_PORT:5432
    volumes:
      - db:/var/lib/postgres

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
volumes:
  db: