version: "3"

services:
  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    restart: always
    ports:
      - 3000:8080
    networks:
      - weird_salads
  postgresdb:
    image: postgres
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATABASE
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PASSWORD
    ports:
      - $PG_PORT:5432
    volumes:
      - db:/var/lib/postgres
    networks:
      - weird_salads
  api:
    container_name: api
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    restart: always
    env_file: ./.env
    environment:
      - POSTGRES_DB=$DATABASE
      - POSTGRES_USER=$PG_USER
      - POSTGRES_PASSWORD=$PASSWORD
      - HOST=postgresdb
      - PG_PORT=5432
    ports:
      - 3001:3001
    networks:
      - weird_salads

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  weird_salads:
    external: true
volumes:
  db: